#Port khi chạy ứng dụng
server:
  port: 8088
  error:
    include-stacktrace: never
  ssl:
    enabled: false
    key-store: /xxx
    key-store-password: xxx
    key-store-type: PKCS12
    key-alias: myserver
spring:
  application:
    name: yte-school-health
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/yte
    username: postgres
    password: 123qwe
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      minimumIdle: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false